Dataset Media Fields
voxel51/fiftyone pull request #1841
Opened 2022-06-08 14:04 UTC by ritch

2022-06-08 14:07 UTC, ritch commented on app/packages/app/src/components/Actions/Options.tsx
> +  console.log(dataset);
This logs:

```
{id: '62a0acd249dac2bfcfa32ccc', name: '2022.06.08.07.06.10', mediaType: 'image', sampleFields: Array(8), frameFields: Array(0), …}
appSidebarGroups: null
brainMethods: []
createdAt: "2022-06-08T14:06:10.175000"
defaultMaskTargets: {}
defaultSkeleton: null
evaluations: []
frameFields: []
id: "62a0acd249dac2bfcfa32ccc"
lastLoadedAt: "2022-06-08T14:06:12.639000"
maskTargets: {}
mediaType: "image"
name: "2022.06.08.07.06.10"
sampleFields: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
skeletons: []
version: "0.16.1"
viewCls: null
```

2022-06-08 16:49 UTC, benjaminpkane commented on fiftyone/core/odm/dataset.py
> +    app_config = EmbeddedDocumentField(document_type=DatasetAppConfigDocument)
```suggestion
    app_config = EmbeddedDocumentField(
        document_type=DatasetAppConfigDocument,
        default=lambda: DatasetAppConfigDocument(
            grid_media_field="filepath", media_fields=["filepath"]
        ),
    )
```

2022-06-08 16:50 UTC, benjaminpkane commented on fiftyone/core/dataset.py
> +        if self._doc.app_config == None:
I think the `default` kwarg can be used when defining the field. Providing a lambda. See suggestion

2022-06-17 14:58 UTC, brimoor requested changes
I propose that we merge this into a `feature/dataset-app-config` feature branch and hold off on releasing until we also expose/migrate all of `fityone.core.config.AppConfig` into `fiftyone.core.odm.DatasetAppConfig` (or decide we never want to do that). My goal is to more fully round out the new `dataset.app_config` concept before releasing.

Other review comments
- Need to add logic in `delete_sample_field()` and `rename_sample_field()` that will appropriately update `DatasetAppConfig.media_fields` as necessary
- Prefer to migrate `app_sidebar_groups` into `app_config.sidebar_groups`, for cleanliness
- These features will need documentation before releasing

2022-06-17 14:58 UTC, brimoor commented on fiftyone/core/dataset.py
> +        self._doc.app_config = config
`self._doc.save()` is needed here

2022-06-17 15:05 UTC, brimoor commented
Following up on some questions from the PR description:

Q: Are we extending these to the global app config as well? What if a dataset does not have the right shape?
A: I don't think we should bring the new `Dataset.app_config` into the `fiftyone.AppConfig` (as pointed out, these new settings depend on the shape of the dataset and thus can't be global). Instead I think we should bring `fiftyone.AppConfig` into `Dataset.app_config` 🤗  There are some order of precedence details to get right

Q: How much validation should be done? E.g. when a media field is deleted. Should we validate grid_media_field is a media_field?
A: I think we should automatically handle deletion/renaming of a field that's included in `media_fields`, but, since we don't have a `MediaField` concept *only a `StringField` that may contain filepaths, but may also just contain "foo" and "bar"), we shouldn't attempt to validate that a `media_fields` choice is valid. Just wait for "invalid image" to appear in the App grid

2022-08-18 16:37 UTC, benjaminpkane commented
Stale. Merged in to #1954

2022-08-18 16:37 UTC, closed without merging