icons for sample types
voxel51/fiftyone pull request #2037
Opened 2022-08-29 22:26 UTC by ritch

<img width="786" alt="Screen Shot 2022-08-29 at 3 16 21 PM" src="https://user-images.githubusercontent.com/462228/187309660-c86e47aa-b2c2-4825-80b0-d9c161b7d167.png">

<img width="416" alt="Screen Shot 2022-08-29 at 3 25 47 PM" src="https://user-images.githubusercontent.com/462228/187309710-38c7b019-99cc-45a4-842e-3d1cafcbc1a7.png">

<img width="416" alt="Screen Shot 2022-08-29 at 3 25 47 PM" src="https://user-images.githubusercontent.com/462228/187309741-a2e58a8a-b688-48e9-aef7-2872b96bd26a.png">

2022-08-30 18:25 UTC, benjaminpkane requested changes
Looks good. I like the orange, but it may be deceiving as it is not a button. Maybe something darker?

2022-08-30 18:25 UTC, benjaminpkane commented on app/packages/app/src/components/ImageContainerHeader.tsx
> +  };
Unused, maybe?

2022-08-30 18:25 UTC, benjaminpkane commented on app/packages/app/src/components/ImageContainerHeader.tsx
> +  );
This is going to suspend, which will yield a bad loading state. It should be used in a component within a `Suspense` like `Count` was previously.

2022-08-30 18:25 UTC, benjaminpkane commented on app/packages/app/src/components/ImageContainerHeader.tsx
> +            title={`${total.toLocaleString()} ${_.capitalize(type)} ${
I don't think the type needs to be capitalized. The values are not capitalized in Python, e.g.:

```
Name:        quickstart
Media type:  image
Num samples: 200
Persistent:  False
Tags:        []
Sample fields:
    id:           fiftyone.core.fields.ObjectIdField
    filepath:     fiftyone.core.fields.StringField
    tags:         fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    ground_truth: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    uniqueness:   fiftyone.core.fields.FloatField
    predictions:  fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
```

2022-09-02 00:29 UTC, brimoor commented
We decided not to add icons right now

2022-09-02 00:29 UTC, closed without merging