Sync router state
voxel51/fiftyone pull request #2230
Opened 2022-11-03 20:33 UTC by benjaminpkane

Resolves #2229. This is a syncing issue with recoil/relay and the url state. @kaixi-wang per you offline comment, Recoil Sync could be a great fit for keeping state in sync. The current implementation isn't ideal.

2022-11-03 21:17 UTC, brimoor requested changes
@benjaminpkane now every time I update the view the entire App reloads. Can you avoid that?

![2022-11-03 17 16 39](https://user-images.githubusercontent.com/25985824/199835898-a38a9f0e-059a-4ea9-9025-79d8c2e752f5.gif)

2022-11-04 23:48 UTC, brimoor commented
@benjaminpkane I am still seeing the issue pictured above. Also setting `session.view = None` gets me to an invalid state pictured below:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-geo")
session = fo.launch_app(dataset)

# Create a Limit(10) stage in the App (whole app refreshes)

session.view = None

# App is now in inconsistent state pictured below
```

<img width="1144" alt="Screen Shot 2022-11-04 at 7 46 57 PM" src="https://user-images.githubusercontent.com/25985824/200090303-9dd0b69a-4f9a-4ba6-9711-e092aa9852a7.png">

2022-11-05 01:34 UTC, kaixi-wang commented
> Resolves #2229. This is a syncing issue with recoil/relay and the url state. @kaixi-wang per you offline comment, Recoil Sync could be a great fit for keeping state in sync. The current implementation isn't ideal.

I'm currently trying to get it working for routing to saved views, but if it works well, we can probably use it for datasets as well.

2022-11-06 17:57 UTC, benjaminpkane commented
Things should work now

2022-11-06 18:39 UTC, brimoor approved these changes
LGTM

2022-11-06 18:39 UTC, brimoor commented on app/packages/state/src/hooks/useSetView.ts
> +              console.log(router.history.location.state);
remove `console.log`?

2022-11-06 18:48 UTC, brimoor requested changes
Hmm okay nevermind, still seeing some state sync issues.

Here's my diagnosis of the GIF:
1. Grid loads wrong number of samples when `limit(5)` view is loaded from Python. I believe the first page of results from the previous state is being shown (not shown in GIF but I cannot scroll past first page). Refreshing in browser resolves the issue
2. Loading `limit(1)` stage now shows first page of previous view's  results in grid
3. Loading `limit(1)` a second time syncs everything correctly, but now the view bar is non-responsive

![2022-11-06 13 43 26](https://user-images.githubusercontent.com/25985824/200189193-954150eb-71fb-4d28-8447-5219217994c1.gif)

2022-11-06 19:03 UTC, benjaminpkane commented
I can't reproduce any of the above. Can you do a clean install and rebuild. And clear your cache, of course.

`cd ./app && rm -rf node_modules && yarn install && yarn build`

2022-11-06 20:28 UTC, brimoor commented
My normal build is to use `install.bash`. I ran `cd ./app && rm -rf node_modules && yarn install && yarn build` this time and am still seeing the issues I reported.

```
sse-starlette==0.10.3
starlette==0.20.4
strawberry-graphql==0.138.1
```

2022-11-07 01:42 UTC, benjaminpkane commented
OK, we will have to take this offline. Still unable to reproduce

2022-11-07 05:59 UTC, merged