fix looker3d controls styles in light theme
voxel51/fiftyone pull request #2236
Opened 2022-11-04 00:59 UTC by imanjra

## What changes are proposed in this pull request?

Improve Looker3D controls styles to make it consistent with looker 2D controls styles 

## How is this patch tested? If it is not, please explain why.

Tested visually in both light and dark theme

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2022-11-04 16:00 UTC, benjaminpkane commented
Looks good. For consistency, can the grey border be removed from the Looker3d controls row? It also looks like the the icons are smaller in Looker3d. And there is no animation on hover, but that is a smaller detail.
<img width="1470" alt="Screen Shot 2022-11-04 at 9 58 07 AM" src="https://user-images.githubusercontent.com/19821840/200021203-74971eec-c8f4-4c02-8030-7ce01a7a7484.png">

2022-11-05 02:35 UTC, brimoor requested changes
@imanjra can you address these related items before merging?

1. Clicking the `?` icon in Looker3D a second time does not close the help menu (it immediately reopens)

2. This Looker3D component needs to respect light theme
<img width="392" alt="Screen Shot 2022-11-04 at 8 05 46 PM" src="https://user-images.githubusercontent.com/25985824/200096926-284c6392-caad-4594-a80b-a1c9c20480b1.png">

3. The close modal buttons are inconsistent in light theme (I think dark color makes sense)
<img width="997" alt="Screen Shot 2022-11-04 at 8 09 12 PM" src="https://user-images.githubusercontent.com/25985824/200096975-0f0af45d-fab2-4118-8757-4583aeddd6f5.png">
<img width="869" alt="Screen Shot 2022-11-04 at 8 08 54 PM" src="https://user-images.githubusercontent.com/25985824/200096976-70a3bbe6-6f3a-4315-aeba-15810681e8fa.png">
<img width="831" alt="Screen Shot 2022-11-04 at 8 05 36 PM" src="https://user-images.githubusercontent.com/25985824/200096977-f7b1c39c-5b50-4257-a385-b5e969c2877b.png">

4. This overlay text should be white in both dark and light theme:

<img width="1167" alt="Screen Shot 2022-11-04 at 8 08 39 PM" src="https://user-images.githubusercontent.com/25985824/200097028-54af5bcd-faff-4d43-b576-a955d083ca9f.png">
<img width="653" alt="Screen Shot 2022-11-04 at 10 28 34 PM" src="https://user-images.githubusercontent.com/25985824/200097284-49294a95-354f-4989-b889-ede6e384f986.png">


5. Remove shadow from Looker3D's toolbar for consistency with Looker2D's toolbar:

<img width="732" alt="Screen Shot 2022-11-04 at 10 25 33 PM" src="https://user-images.githubusercontent.com/25985824/200097087-3528543a-8dad-45ec-9a68-dd421afee5ab.png">
<img width="750" alt="Screen Shot 2022-11-04 at 10 25 29 PM" src="https://user-images.githubusercontent.com/25985824/200097089-3099c6f2-527e-49de-b8b4-f7201ddfde77.png">

6. Use same darker background for JSON viewer that is used in help menu (too difficult to read the JSON viewer currently). Also I think the transparency is too much right now. Better to make it more opaque so the modal text is easier to read:

<img width="769" alt="Screen Shot 2022-11-04 at 10 30 01 PM" src="https://user-images.githubusercontent.com/25985824/200097266-06580df5-77b7-40c9-afce-e7bc850861db.png">
<img width="1099" alt="Screen Shot 2022-11-04 at 10 29 52 PM" src="https://user-images.githubusercontent.com/25985824/200097267-4dae7724-15fc-458c-ae16-67620b647432.png">

2022-11-05 03:24 UTC, ritch approved these changes

2022-11-05 15:13 UTC, brimoor approved these changes
LGTM, thank you @imanjra!

2022-11-05 15:13 UTC, merged