Update notebook screenshots
voxel51/fiftyone pull request #2398
Opened 2022-12-06 02:31 UTC by benjaminpkane

Resolves #2264 
<img width="1470" alt="Screen Shot 2022-12-05 at 8 28 17 PM" src="https://user-images.githubusercontent.com/19821840/205794244-d6914115-1cae-47b7-b9cf-882c9bdc19a9.png">

2022-12-06 03:47 UTC, brimoor requested changes
Most of the issues from #2264 are fixed, but I'm still seeing the checkboxes in the grid after freezing:
<img width="983" alt="Screen Shot 2022-12-05 at 10 39 06 PM" src="https://user-images.githubusercontent.com/25985824/205807256-fdf55962-940b-43fc-aab5-6c2c39503364.png">

I do also now get the following error when trying to open the expanded modal for a grouped dataset on this branch:

```
index.01da734e.js:134 TypeError: Cannot read properties of undefined (reading 'group')
    at thumbnailTitle (index.01da734e.js:1700:2582)
    at z4.renderSelf (index.01da734e.js:750:10502)
    at z4.render (index.01da734e.js:744:297578)
    at index.01da734e.js:744:297668
    at Array.forEach (<anonymous>)
    at X4.render (index.01da734e.js:744:297615)
    at Xst.updater (index.01da734e.js:755:59732)
    at Xst.attach (index.01da734e.js:755:62445)
    at ete.render (index.01da734e.js:1700:3592)
    at index.01da734e.js:1284:3310
```

2022-12-06 03:49 UTC, brimoor commented
Is it straightforward to include the map and Looker3D in the screenshots? https://github.com/voxel51/fiftyone/issues/2264#issuecomment-1338700054

@jacobmarks has a 3D tutorial that he'd like to publish, but is currently blocked because Looker3D is absent from the frozen App images.

2022-12-06 14:16 UTC, brimoor commented
@benjaminpkane Actually looks like the grouped dataset modal error is coming from `develop`, not this branch. Seeing it there too.

2022-12-06 14:18 UTC, benjaminpkane commented
Unrelated, merged develop.
> ```
> index.01da734e.js:134 TypeError: Cannot read properties of undefined (reading 'group')
>     at thumbnailTitle (index.01da734e.js:1700:2582)
>     at z4.renderSelf (index.01da734e.js:750:10502)
>     at z4.render (index.01da734e.js:744:297578)
>     at index.01da734e.js:744:297668
>     at Array.forEach (<anonymous>)
>     at X4.render (index.01da734e.js:744:297615)
>     at Xst.updater (index.01da734e.js:755:59732)
>     at Xst.attach (index.01da734e.js:755:62445)
>     at ete.render (index.01da734e.js:1700:3592)
>     at index.01da734e.js:1284:3310
> ```

2022-12-06 14:19 UTC, benjaminpkane commented
> Most of the issues from #2264 are fixed, but I'm still seeing the checkboxes in the grid after freezing

Can you share steps? My screenshots do not have this issue

2022-12-06 16:01 UTC, brimoor commented
I see the checkboxes just by doing this:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-groups")
session = fo.launch_app(dataset)
```

```py
session.freeze()
```

2022-12-06 16:36 UTC, brimoor commented
@benjaminpkane confirmed that Looker3D now appears in screenshots, but the map doesn't yet.

2022-12-06 20:36 UTC, benjaminpkane commented
WebGL is no captured for both

2022-12-06 20:42 UTC, benjaminpkane commented
All things addressed

2022-12-08 21:22 UTC, brimoor approved these changes
LGTM, all types of screenshots are looking great now 💪  

Is there any low-hanging fruit to speed up the screenshot process? It can take 30 seconds on my machine to screenshot the grid view of a dataset. For reference, I find that it's typically quite a bit faster when the modal is open.

2022-12-08 21:22 UTC, brimoor commented on fiftyone/core/session/notebooks.py
> +def display_databricks(
Remove databricks stuff for clarity?

2022-12-12 17:52 UTC, benjaminpkane commented
[toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) has an optional image quality parameter which I haven tentatively set to 0.25. Example screenshot of quality 0.25 below

<img width="1470" alt="Screen Shot 2022-12-12 at 11 50 08 AM" src="https://user-images.githubusercontent.com/19821840/207117563-10349222-2f0c-4d1f-b451-ae336718db17.png">

2022-12-12 18:08 UTC, merged