Never show expanded list for ID fields
voxel51/fiftyone pull request #2408
Opened 2022-12-06 22:53 UTC by lanzhenw

fixes #2308 

## What changes are proposed in this pull request?
ID list should always be displayed as a filter search, instead of expanded selection options.

## How is this patch tested? If it is not, please explain why.

Locally

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2022-12-06 23:17 UTC, lanzhenw commented on app/packages/core/src/components/Filters/CategoricalFilter.tsx
> +      !NEVEREXPAND_FIELDS.includes(name.toLowerCase())) ||
Yes, I just refactored it.

2022-12-06 23:18 UTC, ShawnOakley approved these changes
LGTM!

2022-12-07 05:28 UTC, brimoor commented on app/packages/core/src/components/Filters/CategoricalFilter.tsx
> +            NEVEREXPAND_FIELDS.includes(name.toLowerCase())) &&
Agree that abstracting this check into a util function would be clean

2022-12-07 05:32 UTC, brimoor requested changes
@lanzhenw one point of clarification that I should have made more clear in the issue description: it would be nice to apply this logic to any field of type `ObjectIdField`. By convention, all `id` fields always have type `ObjectIdField`, but there could be other such fields as well.

For example:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.to_patches("ground_truth")

print(view)
```

has two top-level `ObjectIDField`s:

```
Dataset:     quickstart
Media type:  image
Num patches: 1232
Patch fields:
    id:           fiftyone.core.fields.ObjectIdField
    sample_id:    fiftyone.core.fields.ObjectIdField
    filepath:     fiftyone.core.fields.StringField
    tags:         fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    ground_truth: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detection)
View stages:
    1. ToPatches(field='ground_truth', config=None)
```

2022-12-07 05:36 UTC, brimoor commented
Another point of discussion: one could argue that this "never expand" behavior is primarily important only for nested label attributes such as `ground_truth.detections.id` in the `quickstart` dataset (because multiple widgets appear altogether when the `ground_truth` field's widgets tray is expanded) and *not* the top-level `id` field, since each top-level field has its own expandable filter tray.

Curious what folks think about this?

2022-12-07 23:15 UTC, brimoor commented
Just to clarify: we decided offline to force all `ObjectIdField` fields to use "non-expanded" mode, whether top-level or nested

2022-12-08 00:23 UTC, brimoor requested changes

2022-12-08 00:23 UTC, brimoor commented on app/packages/core/src/components/Filters/CategoricalFilter.tsx
> +  const neverShowExpansion = NEVEREXPAND_FIELDS.includes(name.toLowerCase());
`NEVEREXPAND_FIELDS` is not defined

2022-12-08 20:10 UTC, brimoor approved these changes
LGTM

2022-12-08 20:59 UTC, merged