[wip] groups expansion should be defaulted to none
voxel51/fiftyone pull request #2441
Opened 2022-12-14 17:30 UTC by lanzhenw

fixes #2284 

## What changes are proposed in this pull request?

- set the groups expansion default to none in the BE 
- in the FE, let `resolveGroup` would expand the defaulted open fields

## How is this patch tested? If it is not, please explain why.

(Details)

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-01-03 15:46 UTC, benjaminpkane approved these changes
LGTM!

2023-01-07 20:05 UTC, brimoor requested changes
This is not behaving as I would expect.

First, I get an error when trying to edit the sidebar groups in the App:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)

# Error when dragging `ground_truth` field into `PRIMITIVES` group in sidebar
```

Also, if I define sidebar groups and then switch to fast mode in the App, I expect that the sample/label tags sections will be collapsed by default (which is how fast mode works when there is no `app_config` explicitly defined). However, the tags sections are still expanded:

```py
dataset.app_config.sidebar_groups = fo.DatasetAppConfig.default_sidebar_groups(dataset)
dataset.save()

session.refresh()

# Switch to fast mode under App settings
# Click cube logo in upper left to refresh the App
# The sample/label tags should be collapsed, but they are not
```

2023-01-13 21:49 UTC, benjaminpkane commented
I've test myself and I believe comments are addressed

2023-01-13 23:25 UTC, brimoor approved these changes

2023-01-13 23:25 UTC, brimoor commented
Works, yay! 💪

2023-01-14 03:22 UTC, merged