[WIP] Refactor Tags
voxel51/fiftyone pull request #2557
Opened 2023-01-23 16:21 UTC by lanzhenw

This is what we want to achieve: 
![Screenshot 2023-01-23 at 10 16 36 AM](https://user-images.githubusercontent.com/17770824/214091263-4d2cc1af-2c7e-4df1-be8a-052088fddab3.png)

## What changes are proposed in this pull request?

Refactor tags to treat label tags and sample tags like normal string field. 

- [ ] Make the UI in sidebar setting work: Hard code necessary parts to update sidebar groups so that sidebar would parse sample tags and label tags as `PATH` (currently `GROUP`) and items inside would be `INPUT` instead of `PATH`. 

- [ ] Update filter: Right now we only support filter_label options with the filter tags. With the filter options, we would allow match_labels and exclude. Update the expr part in the backend for corresponding tag selections. 

- [ ] data migration needed

## How is this patch tested? If it is not, please explain why.

(Details)

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-01-23 17:35 UTC, lanzhenw commented
Status update: ![Screenshot 2023-01-23 at 11 32 43 AM](https://user-images.githubusercontent.com/17770824/214109150-5abc78e2-ab56-46aa-a759-bc7c5ce2e6db.png)

2023-03-01 15:05 UTC, benjaminpkane requested changes
Code looks really good!

One thing I noticed in testing is the sidebar is suspending while tag data is loading which is a regression. We want to show the sidebar immediately, which means any recoil value that may suspend (is async with a network request) must be wrapped by a `Suspense` as closely as possible to the component showing that data. Or you can use `useRecoilValueLoadable`

2023-03-03 18:32 UTC, lanzhenw commented on app/packages/core/src/components/SamplesContainer.tsx
> +                childPaths={entry.childPaths}
cleaned it

2023-03-03 18:32 UTC, lanzhenw commented on app/packages/state/src/recoil/sidebar.ts
> +  childPaths?: string[];
I just cleaned it. Thanks for catching it!

2023-03-07 16:25 UTC, brimoor requested changes
@lanzhenw looking good! Here's a couple things I saw:

- Can you update the implementation so that sample tag counts are not computed by default when sidebar mode is "fast"? See below. The intention is that counts are only computed when the sidebar mode is "all" OR the filter tray for that field is expanded
- Can you update the default sidebar groups so that sample tags are above label tags?

<img width="615" alt="Screen Shot 2023-03-07 at 11 20 21 AM" src="https://user-images.githubusercontent.com/25985824/223484637-5756576d-08b1-4774-9662-3ebaee650f0c.png">

2023-03-07 21:52 UTC, lanzhenw commented
> @lanzhenw what's the intended behavior when trying to reorder `tags` and `label tags` in the sidebar? Previously this was not possible (individual tags could not be dragged). Now I am able to, for example, drag `tags` into the `LABELS` section, but then I cannot drag it back.
> 
> Shall we make it so that tags paths cannot be reorganized?

Yes, since tags paths are specially coded, I just made label tag and sample tag undraggable.

2023-03-08 04:34 UTC, brimoor commented
@lanzhenw I'm seeing a couple minor things and one key issue:

## Key issue

- As shown in the screenshot below, sometimes when I select a label tag to filter by, the sidebar and samples count update as expected, but the grid doesn't render. If I click the bookmark icon, then the grid renders correctly. Potentially related? This is a dataset with multiple label fields (`Classification`, `Detections`, and `Polylines`)

<img width="1144" alt="Screen Shot 2023-03-07 at 11 23 05 PM" src="https://user-images.githubusercontent.com/25985824/223620406-c57e1b0a-1d9d-4949-be23-79d78c8abf7c.png">

## Minor issues

- The tags fields cannot actually be dragged, but when you hover over them the "drag mode" still activates, suggesting that you should be able to drag. Can you disable this too?
- When there are no label tags, you cannot click the `label tags` visibility checkbox, whereas other fields with a count of zero still allow you to click the checkbox

<img width="301" alt="Screen Shot 2023-03-07 at 11 22 22 PM" src="https://user-images.githubusercontent.com/25985824/223619834-2ee9b26f-d02b-4261-937b-b34a1a35d5be.png">

## Not strictly related to this PR, but can you look at it? 🤗 

- Certain fields (`Polylines` and `StringField`) with a count of zero allow their filter tray to be expanded, showing a "No results" state like shown below. However, other fields (`Detections` and `IntField`) immediately collapse after you try to open them if the count is zero. This makes it a bit confusing whether the field is actually expanded or not. It would be preferable if all filter trays could be opened, showing an appropriate "No results" state if necessary

<img width="285" alt="Screen Shot 2023-03-07 at 11 24 02 PM" src="https://user-images.githubusercontent.com/25985824/223619853-13183840-f33a-4fca-95a4-e684d23e529a.png">

2023-03-09 00:03 UTC, lanzhenw commented
@brimoor Thanks for catching the issues. Got them fixed.
Key issue: 
https://user-images.githubusercontent.com/17770824/223880609-e788426f-6484-48d5-9b9d-69e9c1a50bcf.mov
Minor issues:
https://user-images.githubusercontent.com/17770824/223880802-ba949423-77b6-4387-b1b6-c7ccf4ba7b11.mov

2023-03-09 00:22 UTC, brimoor approved these changes
I defer to @benjaminpkane for final code approval, but usability is great. Nice work @lanzhenw! 💪

2023-03-09 16:36 UTC, benjaminpkane commented on app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
> +      const labels = get(labelTagsCount({ modal, extended: false }));
It's better to subscribe to `labelTagsCount` only when `isLabelTag` is true

2023-03-09 16:39 UTC, benjaminpkane commented on app/packages/core/src/components/Sidebar/Entries/EntryCounts.tsx
> +      if (!r1) return { count: 0, results: [] };
Maybe these variable names could be more descriptive? Just a suggestion

2023-03-09 23:34 UTC, benjaminpkane approved these changes
LGTM! I don't believe my updates broke anything, but please let me know if I did.

2023-03-10 05:37 UTC, merged