Empty samples page with reset button
voxel51/fiftyone pull request #2734
Opened 2023-03-06 22:13 UTC by manivoxel51

## What changes are proposed in this pull request?

Show a better message when there are no samples matching the active view + a reset view button.

https://user-images.githubusercontent.com/109545780/223246342-dfd3f94f-0943-4377-a55e-da2ae2f79cd3.mov

(Please fill in changes proposed in this fix)

## How is this patch tested? If it is not, please explain why.

(Details)

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-03-07 01:40 UTC, sashankaryal commented on app/packages/core/src/components/EmptySamples.tsx
> +  const loadedView = useRecoilValue<fos.State.Stage[]>(fos.view);
nit: type parameter implicitly derived

2023-03-07 01:40 UTC, sashankaryal commented on app/packages/core/src/components/EmptySamples.tsx
> +  if (!showEmptySamples) return null;
nit: newline before return

2023-03-07 01:43 UTC, sashankaryal approved these changes
lgtm but i might not have the broadest context in terms of specs

2023-03-07 02:09 UTC, brimoor requested changes
Thanks for adding this!

**Functional comment:** can you also handle the case where it is an empty *dataset* rather than a view? When the dataset itself is empty, there's no need for a "clear view" button, the user just needs to know that their dataset is empty:

```py
import fiftyone as fo

dataset = fo.Dataset()
session = fo.launch_app(dataset)
```

**For fun:** what do you think of showing the 404 image from Teams instead? Potential layout:

```
[image]
Your view is empty
[Clear view button]
```

<img width="957" alt="Screen Shot 2023-03-06 at 9 04 15 PM" src="https://user-images.githubusercontent.com/25985824/223301282-8138e037-cd6c-489e-8713-a1c4646dfb7b.png">

2023-03-07 19:14 UTC, manivoxel51 commented
> Thanks for adding this!
> 
> **Functional comment:** can you also handle the case where it is an empty _dataset_ rather than a view? When the dataset itself is empty, there's no need for a "clear view" button, the user just needs to know that their dataset is empty:
> 
> ```python
> import fiftyone as fo
> 
> dataset = fo.Dataset()
> session = fo.launch_app(dataset)
> ```
> 
> **For fun:** what do you think of showing the 404 image from Teams instead? Potential layout:
> 
> ```
> [image]
> Your view is empty
> [Clear view button]
> ```
> 
> <img alt="Screen Shot 2023-03-06 at 9 04 15 PM" width="957" src="https://user-images.githubusercontent.com/25985824/223301282-8138e037-cd6c-489e-8713-a1c4646dfb7b.png">

good idea!
I am thinking having both use the same design (our 404 page in teams) make sense too. I'll adapt the pr to
1. show empty page with image + `Your view is empty` title as text and `clear view` as button when there are view stages
2. show empty page with image + `Your dataset is empty` as title, no clear button. also, maybe add a code snippet here to show how to bring data into an existing dataset? or just leave the code snippet out

@brimoor what do you think?

2023-03-07 22:32 UTC, brimoor commented
Rather than including a code snippet for the empty dataset case, you could just link to this page on the topic:
https://docs.voxel51.com/user_guide/dataset_creation/index.html

2023-03-09 00:11 UTC, brimoor approved these changes
LGTM

2023-03-09 02:28 UTC, merged