fix sort video groups
voxel51/fiftyone pull request #3614
Opened 2023-10-03 10:16 UTC by sashankaryal

## What changes are proposed in this pull request?

#### Previous Aggregation Pipeline

The previous pipeline (somewhat inexplicably) outputs an unstable ordering of documents. While the group stage doesn't guarantee a stable sort, the absence of the lookup stage, which adds the sorted frames object from the frames collection, results in a stable order of documents. This might be due to the presence of a nested field object, such as frames, outputted by the lookup stage, which could be affecting how the group stage operates.

```
[
  {
    $lookup: {
      from: "frames.samples.6421c8af194325086c697069",
      let: {
        sample_id: "$_id",
      },
      pipeline: [
        {
          $match: {
            $expr: {
              $eq: ["$$sample_id", "$_sample_id"],
            },
          },
        },
        {
          $sort: {
            frame_number: 1,
          },
        },
      ],
      as: "frames",
    },
  },
  {
    $sort: {
      "metadata.duration": 1,
      "metadata.size_bytes": 1,
    },
  },
  {
    $group: {
      _id: "$metadata.duration",
      doc: {
        $first: "$$ROOT",
      },
    },
  },
  {
    $replaceRoot: {
      newRoot: "$doc",
    },
  },
]
```

#### New Aggregation Pipeline

This PR solves the unstable sort problem by applying the `sort` stage _after_ the `group` stage.

```
[
  {
    $lookup: {
      from: "frames.samples.6421c8af194325086c697069",
      let: {
        sample_id: "$_id",
      },
      pipeline: [
        {
          $match: {
            $expr: {
              $eq: ["$$sample_id", "$_sample_id"],
            },
          },
        },
        {
          $sort: {
            frame_number: 1,
          },
        },
      ],
      as: "frames",
    },
  },
  {
    $group: {
      _id: "$metadata.duration",
      doc: {
        $first: "$$ROOT",
      },
    },
  },
  {
    $replaceRoot: {
      newRoot: "$doc",
    },
  },
    {
    $sort: {
      "metadata.duration": 1,
      "metadata.size_bytes": 1,
    },
  },
]
```

## How is this patch tested? If it is not, please explain why.

Locally.

## Release Notes

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-10-03 11:57 UTC, brimoor requested changes
The reason that sorting comes before grouping in the current implementation is that it’s trying to guarantee that the $first doc that is chosen to represent each group is the lowest wrt `order_by` within each group.

For example in 

```py
view = dataset.group_by(“sample_id”, order_by=“frame_number”)
```

it’s trying to guarantee that when you load `view` in the sample grid you see frame number 1 for each group.

I guess the problem you’re trying to solve is that the order of the sample IDs in `view` may not be deterministic when the $sort stage is not the first in the pipeline? The user could fix that by appending a `sort_by(“sample_id”)` stage if they wanted. But maybe you *need* the order to always be deterministic for App navigation?

2023-10-03 17:47 UTC, sashankaryal commented
> The reason that sorting comes before grouping in the current implementation is that it’s trying to guarantee that the $first doc that is chosen to represent each group is the lowest wrt `order_by` within each group.
> 
> For example in
> 
> ```python
> view = dataset.group_by(“sample_id”, order_by=“frame_number”)
> ```
> 
> it’s trying to guarantee that when you load `view` in the sample grid you see frame number 1 for each group.
> 
> I guess the problem you’re trying to solve is that the order of the sample IDs in `view` may not be deterministic when the $sort stage is not the first in the pipeline? The user could fix that by appending a `sort_by(“sample_id”)` stage if they wanted. But maybe you _need_ the order to always be deterministic for App navigation?

Thanks for flagging that. I added a new sort stage at the end of the pipeline to guarantee a deterministic behavior.

Note: We need to guarantee a deterministic ordering because we implement pagination with a new aggregation per query with `.skip()` as opposed to reusing the same cursor.

2023-10-04 17:08 UTC, brimoor approved these changes

2023-10-04 17:08 UTC, brimoor commented on fiftyone/core/stages.py
> +        pipeline.extend(
not: just use append() directly, not extend() with one element list

2023-10-05 06:48 UTC, merged