Fix issue  #3457 :  Error while uploading to labelbox for annotations
voxel51/fiftyone pull request #3635
Opened 2023-10-06 07:50 UTC by ashish-dahal

## What changes are proposed in this pull request?

Fix issue  #3457  (minor change)

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-10-22 22:41 UTC, brimoor commented
@ashish-dahal I see that you closed the underlying issue https://github.com/voxel51/fiftyone/issues/3457. Does that mean that this PR is no longer needed?

2023-10-22 22:43 UTC, brimoor requested changes

2023-10-22 22:43 UTC, brimoor commented on fiftyone/core/annotation.py
> +Annotation utilities.
There should not be any changes to `fiftyone.core.annotations`.

2023-10-22 22:43 UTC, brimoor commented on fiftyone/utils/annotations.py
> +        content_type (None): specified the mime type of the provided samples.
`Sample.filepath` is always available, so the only reason I could see needing to manually specify `content_type` is if you had a BMP-formatted image stored with a `.jpg` extension for something like that.

2023-10-23 16:08 UTC, ashish-dahal commented
> @ashish-dahal I see that you closed the underlying issue #3457. Does that mean that this PR is no longer needed?

Yes, I found a simple fix: The Labelbox SDK uses the Python [`mimetypes`](https://docs.python.org/3/library/mimetypes.html#module-mimetypes) to infer image mime types. This, in turn, looks up mime types from `/etc/mime.types` on Linux. On the Databricks cluster I was using, the mime type for BMP images was `image/x-ms-bmp` instead of the expected `image/bmp`, causing Labelbox to throw an incorrect mime error. Solution was to simply update the mime type entry for BMP images in `/etc/mime.types`  to the correct value.

2023-10-23 16:11 UTC, brimoor commented
Thanks for closing the loop on this! Will close the PR since a solution has been found 👍

2023-10-23 16:11 UTC, closed without merging