[Proposal] add support for datasetless operator
voxel51/fiftyone pull request #3773
Opened 2023-11-03 16:31 UTC by imanjra

## What changes are proposed in this pull request?

(Please fill in changes proposed in this fix)

## How is this patch tested? If it is not, please explain why.

(Details)

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2023-11-06 20:34 UTC, ritch commented on fiftyone/operators/operator.py
> +        datasetless (False): whether the operator can be executed without dataset
This needs more clarification

2023-11-06 20:35 UTC, ritch requested changes
All looks good implementation wise. The doc could use some additional explanation.

2023-11-07 02:14 UTC, brimoor commented
Per offline discussion, decided to hold off on this for now until we consider other alternatives like `resolve_listing()`.

2023-11-07 16:26 UTC, imanjra commented
Closing for now

2023-11-07 16:26 UTC, closed without merging