Session.wait(): add support for remote sessions and attempt to detect when it should be used
voxel51/fiftyone pull request #523
Opened 2020-09-10 21:54 UTC by lethosor

## What changes are proposed in this pull request?

* Fixes #281 by attempting to detect when a session is destroyed soon after it is created and printing a message suggesting the use of `.wait()`.
* Fixes #451 by allowing `.wait()` to work for remote sessions. See the issue for rationale. Note that this never returns under normal circumstances, so a warning about that might be helpful.

## How is this patch tested? If it is not, please explain why.

Tests + some additional local testing

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Added support for calling `wait()` on remote sessions
(The other point from above may not be worth mentioning, since it's fairly self-explanatory to anyone who sees the message)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

2020-09-11 18:18 UTC, benjaminpkane approved these changes
LGTM! It's all in the details.

2020-09-11 18:20 UTC, benjaminpkane requested changes
Actually, I'm just saw that the windows tests are failing. Blocking for now until one of us works through it.

2020-09-11 23:26 UTC, lethosor commented
I was wondering if it would work on Windows but forgot to check... looks like it's just a test issue due to newline conversion (printing \n on Windows prints \r\n, but the test isn't accounting for that).

2020-09-14 01:39 UTC, benjaminpkane approved these changes

2020-09-14 13:51 UTC, lethosor commented
Thanks!

2020-09-14 13:52 UTC, merged