[WIP] Colab and Jupyter notebook support, Official PyPi server hosting, web support
voxel51/fiftyone pull request #706
Opened 2020-12-04 21:27 UTC by benjaminpkane

## What changes are proposed in this pull request?

* Adds web support, e.g. opening the App directly from the browser when a remote session has been forwarded to your machine
* Adds support for Google Colab and Jupyter notebooks
* Changes builds to publish to the official pypi server

I am proposing the simple install no longer includes the app, but includes web support.
```
pip install fiftyone
```

And to install the App, as well
```
pip install fiftyone[app] # or fiftyone[desktop]
```

Fixes #705. Previously, a React hook would begin to repeatedly update state when the label filter was used and freeze up the window

TODOs:
* [ ] Video is not fully functional at the moment. It looks like Colab strips response headers in its proxy so range requests are not handled by HTML5 video elements, i.e. the entire video has to load and seeking behavior does not work. Looking into it
* [ ] Finish github actions updates
* [ ] Finish App packaging updates
* [ ] Update various help outputs
* [ ] Update documentation
* [ ] Test, test, test

## How is this patch tested? If it is not, please explain why.

Locally

## Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

To do...

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [x] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [x] Documentation: FiftyOne documentation changes
-   [ ] Other

2020-12-10 21:07 UTC, benjaminpkane commented
Ready for review

2020-12-14 22:07 UTC, brimoor requested changes
Awesome stuff! I jotted down the comments I had that we discussed online.

The one other comment is to update the main `README.md` with:

(a) Updated instructions for performing a source install such that one can launch the App via either browser (or desktop, if possible?)  and develop non-App code

(b) Updated instructions for developing the App

2020-12-14 22:07 UTC, brimoor commented on fiftyone/core/config.py
> +        self.do_not_track = self.parse_bool(
Suggestion: add an FAQ question that references the existence of this parameter and describes how we track (anonymous) usage

2020-12-14 22:07 UTC, brimoor commented on fiftyone/core/session.py
> +def launch_app(dataset=None, view=None, port=5151, remote=False, window=None):
Suggestion: always print a message when `launch_app()` runs that explains what to expect:

- `desktop=False` (browser): open localhost:<port> in your browser
- `desktop=True` (desktop): FiftyOne desktop App has launched
- notebook: run `session.show()` to open the App in a cell

2020-12-14 22:07 UTC, brimoor commented on fiftyone/utils/uid.py
> +def _get_user_id():
Leaving myself a note to investigate when this message is printed during normal usage

2020-12-15 15:09 UTC, benjaminpkane commented
Thanks for the thorough feedback! All comments have been addressed.

2020-12-17 17:04 UTC, brimoor commented
@benjaminpkane Now that people are very likely to see the "You are not connected to a session" page in the App (eg whenever they exist a Python shell with a browser session open), can you update the text there?

Here's my suggestion for the text:

**Local sessions**

~~The following demonstrates how to connect to a local session from a python shell~~

Here's how to connect to a local session from Python:

```py
import fiftyone as fo

# Load your FiftyOne dataset
dataset = fo.load_dataset(...)

# Launch the app
session = fo.launch_app(dataset)
```

<img width="1043" alt="Screen Shot 2020-12-17 at 11 37 51 AM" src="https://user-images.githubusercontent.com/25985824/102517986-b738f980-405e-11eb-8c92-52400e268370.png">

**Remote sessions**

You can work with data on a remote machine by launching a remote App session and connecting to it from your local machine. [See this page](https://voxel51.com/docs/fiftyone/user_guide/app.html#remote-sessions) for more information.

On your remote machine

```py
import fiftyone as fo

# Load your FiftyOne dataset
dataset = fo.load_dataset(...)

# Launch a remote App instance that you'll connect to from your local machine
session = fo.launch_app(dataset, remote=True, port=XXXX)
```

On your local machine

```shell
# Option 1
# Use the CLI to configure port forwarding
# Connect to first remote session
fiftyone app connect \
    --destination <username>@<remote-ip-address> \
    --port XXXX --local-port 5151

# Option 2
# Manually configure port forwarding
ssh -N -L 5151:127.0.0.1:XXXX <username>@<remote-ip-address>
```

~~Port configuration~~

~~The default FiftyOne port is 5151. You can configure at anytime using the settings tab.~~

<img width="966" alt="Screen Shot 2020-12-17 at 11 38 06 AM" src="https://user-images.githubusercontent.com/25985824/102517979-b30cdc00-405e-11eb-87f2-2eb20fe7d267.png">

2020-12-17 17:06 UTC, brimoor commented
^the `5151` in the above example would ideally dynamically match the localhost port in browser mode. I guess in desktop mode, the Port configuration message at the bottom would still make sense.

2020-12-17 17:59 UTC, benjaminpkane commented
Ok, ran into an issue which added some time to this. Here is the new setup page. The instructions use the active port number.

![Screenshot from 2020-12-17 10-57-26](https://user-images.githubusercontent.com/19821840/102524855-c4ea8100-4056-11eb-9196-6c715d0e6131.png)
![Screenshot from 2020-12-17 10-57-11](https://user-images.githubusercontent.com/19821840/102524859-c5831780-4056-11eb-82e8-581e33b02c6c.png)

2020-12-17 18:04 UTC, benjaminpkane commented
Let me add a different notebook instructions page. If they restart the kernel, the setup page is shown.

2020-12-17 18:12 UTC, benjaminpkane commented
Notebook setup:
![Uploading Screenshot from 2020-12-17 11-11-55.png…]()

2020-12-17 18:24 UTC, brimoor commented
Is it easy to change the hyperlink styling of `this page` so it is clear that it is a link?

Not critical by any means, but is it easy to do some basic syntax highlighting on the code snippets?

Great idea on a different notebook startup screen. Since you'd only see this in a cell that already has a `Session` defined, what about changing the help text to simply say:

```
Notebook sessions
-------------------

Re-run this cell to launch the App.
```

2020-12-17 18:37 UTC, benjaminpkane commented
Right, I'll fix the link.

On the second point, If a notebook app cannot connect (like when the kernel is restarted) is means that `session` object does not exist.

2020-12-17 18:51 UTC, brimoor commented
> On the second point, If a notebook app cannot connect (like when the kernel is restarted) is means that the `session` object does not exist.

Yeah, what I meant is that there must have already been code written (but not yet run) in the cell in order for there to be an unconnected App window there. So all the user needs to do is rerun the cell (and prior ones, likely) and then they'll have both their `session` object and their App window

2020-12-17 19:07 UTC, benjaminpkane commented
Ok, I changed the text to:

```
Re-run the cell that created the session shown here
```

2020-12-17 20:31 UTC, brimoor commented
Couple small comments per live discussion:

- Make `session.show()` call `session.refresh()` internally so that any dataset changes will be reflected when the App reloads

- Tweak link style (color and/or underline?) on "click here" so that it is a more obvious click target:

<img width="985" alt="Screen Shot 2020-12-17 at 3 26 12 PM" src="https://user-images.githubusercontent.com/25985824/102540297-d21a6680-407c-11eb-8aff-b2fc4a14d560.png">

2020-12-17 20:36 UTC, brimoor commented
Oh and also I noticed that `session.show(height=100)` didn't seem to have any effect (window was still full width).

This isn't that critical (always full width in notebooks seems best anyway), just observing.

2020-12-17 20:59 UTC, brimoor commented on fiftyone/core/session.py
> +html_escape = html.escape
unnecessary?

2020-12-17 21:06 UTC, benjaminpkane commented on fiftyone/core/session.py
> +html_escape = html.escape
Yes, will remove

2020-12-17 21:43 UTC, benjaminpkane commented
Comments addressed

2020-12-17 22:03 UTC, brimoor approved these changes
Amazing stuff! Everything I've tried is working smoothly 🚀 🔥

2020-12-17 22:21 UTC, merged