Create searchable cards for the Model Zoo docs
voxel51/fiftyone pull request #759
Opened 2021-01-08 22:46 UTC by ehofesmann

Automatically generate cards to be added to `docs/source/user_guide/model_zoo/index.rst` allowing you to search for models by tags from the model zoo.

This is currently only for the model zoo because the dataset zoo does not have as many datasets or tags to search by. I want to update the pytorch sphinx theme to:
1) Make the cards smaller
2) Be able to scroll through them instead of pages

I'd want to add it to the dataset zoo after that.

![image](https://user-images.githubusercontent.com/21222883/104072242-d697f200-51d8-11eb-922b-d75f7d327542.png)

![image](https://user-images.githubusercontent.com/21222883/104072262-e1eb1d80-51d8-11eb-82da-b1ccb2bb0d4a.png)

![image](https://user-images.githubusercontent.com/21222883/104072272-ec0d1c00-51d8-11eb-979d-16d773821016.png)

### You have to click on different pages to navigate through models
![image](https://user-images.githubusercontent.com/21222883/104072305-fe875580-51d8-11eb-88f1-765f5f8794c4.png)

### Multiple selections are `or` rather than `and` 
![image](https://user-images.githubusercontent.com/21222883/104072351-12cb5280-51d9-11eb-809e-9f9fcc3144ab.png)

2021-01-08 22:56 UTC, brimoor requested changes
Awesome that you got this working!

What do you think about moving this to `model_zoo/models.rst` to replace the existing HTML tables, rather than including on the `model_zoo/index.rst` page? This interactive listing is strictly an improvement over the tables over there.

You could delete the currently separate TF and Torch tables and use your single interactive listing instead.

Another benefit of that is that the generation could be fully automatic (note that `docs/generate_docs.bash` automatically generates the `model_zoo/models.rst` file from source using the `docs/scripts/make_model_zoo_docs.py` script. That was a late-breaking addition I snuck into the last release rather than the manual copy+paste that was originally in https://github.com/voxel51/fiftyone/pull/739.

The reason I made `model_zoo/models.rst` separate from `model_zoo/index.rst` is that I was concerned about the landing page being too dense with content. With that being said, it would be nice to have a more obvious visual indication on the landing page that compels the reader to click through to the actual models. I'll think about that.

2021-01-11 15:08 UTC, ehofesmann commented
> Awesome that you got this working!
> 
> What do you think about moving this to `model_zoo/models.rst` to replace the existing HTML tables, rather than including on the `model_zoo/index.rst` page? This interactive listing is strictly an improvement over the tables over there.
> 
> You could delete the currently separate TF and Torch tables and use your single interactive listing instead.
> 
> Another benefit of that is that the generation could be fully automatic (note that `docs/generate_docs.bash` automatically generates the `model_zoo/models.rst` file from source using the `docs/scripts/make_model_zoo_docs.py` script. That was a late-breaking addition I snuck into the last release rather than the manual copy+paste that was originally in #739.
> 
> The reason I made `model_zoo/models.rst` separate from `model_zoo/index.rst` is that I was concerned about the landing page being too dense with content. With that being said, it would be nice to have a more obvious visual indication on the landing page that compels the reader to click through to the actual models. I'll think about that.

Done, for now I've moved the cards over to `model_zoo/models.rst`. I also like having an easily navigatable model listing in `index.rst` but that should probably wait until I've reformatted the cards to be smaller/easier to click through.

2021-01-11 16:08 UTC, brimoor submitted a review, later dismissed
LGTM; thanks for migrating to `models.rst` for now.

I agree with your future work idea to decrease the size of the cards. They're a bit big for such a large list of models (would also be nice to increase the pagination so more results can be seen)

2021-01-11 16:25 UTC, brimoor commented on docs/source/custom_directives.py
> +        if image:
There was a bug here that prevented images from appearing on the tutorial/recipe cards that *do* have images. It's fixed now

2021-01-11 16:25 UTC, brimoor approved these changes
LGTM now (fixed a bug)

2021-01-11 16:30 UTC, merged